version: '3.4'

x-db-variables: &db-variables
  POSTGRES_DB: ${POSTGRES_DB:-postgres}
  POSTGRES_USER: ${POSTGRES_USER:-irusland}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-irusland}
  POSTGRES_HOST: ${POSTGRES_HOST:-localhost}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}

services:
  db:
    image: postgres:latest
    environment:
      <<: *db-variables
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
    - "8000:8000"
    command:
    - python3
    - -m
    - uvicorn
    - api.main:app
    - --host
    - 0.0.0.0
    volumes:
      - ./:/app
    restart: unless-stopped
    environment:
      <<: *db-variables
    depends_on:
    - db

volumes:
  postgres_data:
