services:
  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
    - "8000:8000"
    command:
    - python3
    - -m
    - uvicorn
    - api.main:app
    - --host
    - 0.0.0.0
    volumes:
      - ./:/app

  api2:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
    - "8001:8001"
    command:
    - python3
    - -m
    - uvicorn
    - api.main:app
    - --host
    - 0.0.0.0
    - --port
    - "8001"
    volumes:
      - ./:/app
