"""messages_ts_index

Revision ID: 2541bc6597ed
Revises: 8b5f8e02228f
Create Date: 2023-04-14 23:06:40.889119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2541bc6597ed'
down_revision = '8b5f8e02228f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tsvector_text', 'messages', [sa.text("to_tsvector('russian'::regconfig, text::text)")], unique=False, postgresql_using='GIN')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tsvector_text', table_name='messages', postgresql_using='GIN')
    op.drop_table('messages')
    # ### end Alembic commands ###
