"""users ts index

Revision ID: 323629b28746
Revises: 2541bc6597ed
Create Date: 2023-04-14 23:32:16.663789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "323629b28746"
down_revision = "2541bc6597ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tsvector_name_about",
        "users",
        [sa.text("to_tsvector('russian'::regconfig, name || ' ' || about)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tsvector_name_about", table_name="users", postgresql_using="gin")
    # ### end Alembic commands ###
