"""Create tables

Revision ID: bddbbb066c16
Revises: 
Create Date: 2023-03-24 10:06:46.753301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bddbbb066c16"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chats")
    # ### end Alembic commands ###
